import {
  index,
  layout,
  route,
  type RouteConfig,
} from "@react-router/dev/routes";

export default [
  layout("routes/app-layout.tsx", [
    index("routes/home.tsx"),
    route("territory", "routes/territory.tsx"),
    route("leads/new", "routes/send-lead.tsx"),
    route("leads", "routes/leads.tsx"),
    route("leads/:leadId", "routes/lead-detail.tsx"),
    route("directory", "routes/directory.tsx"),
    route("directory/:representativeId", "routes/representative-detail.tsx"),
    route("notifications", "routes/notifications.tsx"),
    route("insights", "routes/insights.tsx"),
    route("data-status", "routes/data-status.tsx"),
    route("profile", "routes/profile.tsx"),
    route("help", "routes/help.tsx"),
    route("help/requests/:requestId", "routes/help-request.tsx"),
    route("help/:topicSlug", "routes/help-topic.tsx"),
  ]),
  route("sign-in", "routes/sign-in.tsx"),
  route("auth/return", "routes/auth-return.tsx"),
  route("sign-in/help", "routes/sign-in-help.tsx"),
  route("session-expired", "routes/session-expired.tsx"),
  route("access-required", "routes/access-required.tsx"),
  route("access-denied", "routes/access-denied.tsx"),
  route("account-unavailable", "routes/account-unavailable.tsx"),
  route("signed-out", "routes/signed-out.tsx"),
  route("offline", "routes/offline.tsx"),
  route("maintenance", "routes/maintenance.tsx"),
  route("update-required", "routes/update-required.tsx"),
  route("error", "routes/error.tsx"),
  route("access-changed", "routes/access-changed.tsx"),
  route("unsupported-browser", "routes/unsupported-browser.tsx"),
  route("not-found", "routes/not-found.tsx"),
  route("*", "routes/catch-all.tsx"),
] satisfies RouteConfig;
